# name of your application
APPLICATION = gnrc_upd_echo

# If no BOARD is found in the environment, use this default:
BOARD ?= native

# This has to be the absolute path to the RIOT base directory:
RIOTBASE ?= $(CURDIR)/../..

BOARD_INSUFFICIENT_MEMORY := arduino-duemilanove arduino-nano arduino-uno

# Comment this out to disable code in RIOT that does safety checking
# which is not needed in a production environment but helps in the
# development process:
DEVELHELP ?= 1

# Change this to 0 show compiler invocation lines by default:
QUIET ?= 1
#
USEMODULE += gnrc_netdev_default
USEMODULE += auto_init_gnrc_netif
# Activate ICMPv6 error messages
USEMODULE += gnrc_icmpv6_error
# Specify the mandatory networking modules for IPv6 and UDP
USEMODULE += gnrc_ipv6_router_default
USEMODULE += gnrc_udp
# This application dumps received packets to STDIO using the pktdump module
USEMODULE += gnrc_pktdump
# Additional networking modules that can be dropped if not needed
USEMODULE += gnrc_icmpv6_echo
# Add also the shell, some shell commands
USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += ps
USEMODULE += fmt
USEMODULE += xtimer
USEMODULE += gnrc_sock_udp

# We use only the lower layers of the GNRC network stack, hence, we can
# reduce the size of the packet buffer a bit
CFLAGS += -DGNRC_PKTBUF_SIZE=512
# # Define UDP port
DUDP_ECHO_DEFAULT_PORT ?= 8888
CFLAGS += -DUDP_ECHO_PORT=$(DUDP_ECHO_DEFAULT_PORT)
# # Define UDP echo delay in seg
DUDP_ECHO_DEFAULT_DELAY ?= 1
CFLAGS += -DUDP_ECHO_DELAY=$(DUDP_ECHO_DEFAULT_DELAY)

include $(RIOTBASE)/Makefile.include
